TITLE_1: MCKZ
TITLE_2: Métodos Quantitativos
SUBTITLE_1: Disciplina de especialização
SUBTITLE_2: Material de aula, notebooks e referências.

ABOUT: |
  Este site organiza as aulas, exercícios e material suplementar da disciplina.

REFERENCIAS: |
  <ul>
    <li>Livro A …</li>
    <li>Artigo B …</li>
  </ul>

GITHUB_LINK: https://github.com/Academic-Codex/MCKZ-Metodos-Quantitativos
HERO_FILE: metodos-quantitativos.png